"use strict";

// ---------------------------------------------------------------------------
// Verified research data (October 2026). Every phone, email and website status
// below was confirmed by resolving the domain and reading the destination page.
// ---------------------------------------------------------------------------
module.exports = [
  {
    slug: "barkleys-jewelry-and-pawn",
    name: "Barkley's Jewelry and Pawn",
    short: "Barkley's",
    monogram: "BP",
    logo: "logo.jpg",
    logoStyle: "mark",
    theme: "classic",
    kind: "Pawn shop & jewelry store",
    tagline: "Family-owned since 1995 - jewelry, watches, gold and firearms",
    city: "Woodburn, Oregon",
    address: "894 N Pacific Hwy",
    cityLine: "Woodburn, OR 97071",
    phone: "(503) 982-2033",
    phoneAlt: "",
    phoneHref: "tel:+15039822033",
    email: "",
    hours: [
      ["Monday - Friday", "10:00 am - 6:00 pm"],
      ["Saturday", "10:00 am - 5:00 pm"],
      ["Sunday", "Closed"],
    ],
    website: "barkleyspawn.com",
    websiteStatus: "HAS A WEBSITE",
    websiteNote:
      "barkleyspawn.com resolves and redirects to pawncept.com, a live storefront listing the Woodburn store. Not a no-website prospect.",
    accent: "#b45309",
    accentDark: "#92400e",
    about:
      "Barkley's Jewelry and Pawn has been part of the Woodburn community since 1995. We are a family-run shop that buys, sells and trades jewelry, watches, gold, firearms and everyday gear - and when you need cash quickly we offer fast, friendly collateral loans with renewable terms.",
    services: [
      ["Collateral loans", "Fast cash against jewelry, tools, firearms and more, with renewable terms."],
      ["Gold buying", "Scrap gold, broken jewelry and dental gold turned into cash the same day."],
      ["Jewelry & watch repair", "Battery replacement, band sizing and repair on most wrist watches."],
      ["Rings & fine jewelry", "New and pre-owned engagement rings, sterling silver and gemstones."],
      ["Watches & timepieces", "Modern and vintage watches, plus in-house battery service."],
      ["Firearms", "Licensed FFL dealer with new and used firearms, inspected and guaranteed."],
      ["Instruments & gear", "Used guitars, amplifiers and music gear bought and sold."],
      ["Estate purchases", "We buy estate items and large collections - we'll even make house calls."],
    ],
    highlights: [
      ["30+", "years serving Woodburn"],
      ["2", "locations - Woodburn & Salem"],
      ["Same-day", "collateral loans"],
    ],
    reviews: [
      [
        "I love this pawn shop, they have so many little treasures for sale at amazing prices. The owner Mark is so nice & so are all the workers especially Andy & Yanira.",
        "Elysia G.",
        5,
      ],
      [
        "If you're looking for a FFL this is a great option if you're local to Woodburn. The service is friendly, they have a large selection of tools and ammunition.",
        "Christian W.",
        4,
      ],
    ],
    faqs: [
      ["Do I need an appointment?", "No. Walk in during business hours and we will take care of you at the counter."],
      ["What do you take for loans?", "Jewelry, watches, gold, firearms, tools, electronics, instruments and more."],
      ["Do you buy gold that is broken?", "Yes. Scrap gold, broken chains and dental gold are all welcome."],
    ],
    contactNote: "Walk in during opening hours - no appointment needed.",
    servicesTitle: "What's behind the counter",
    servicesIntro:
      "Cash loans, gold buying, jewelry repair and a floor full of treasures - all in one Woodburn storefront.",
    servicesLead: "Loans, buys, sales and repairs - everything we do, listed out.",
    process: {
      title: "How a pawn loan works",
      text: "Ten minutes at the counter, cash in your hand.",
      steps: [
        ["Bring it in", "Walk in with jewelry, tools, firearms or guitars - no appointment needed."],
        ["We value it together", "We appraise it at the counter and explain what it's worth and why."],
        ["Walk out with cash", "Agree the number, sign, and you're done - money in hand the same visit."],
        ["Get it back", "Pay off the loan whenever you like and pick your item back up."],
      ],
    },
    storyTitle: "More than thirty years on Pacific Highway",
    values: [
      ["Family run since 1995", "Mark and the family have been behind this counter for three decades."],
      ["Straight offers", "We tell you what it's worth before we ever talk numbers."],
      ["Everyone's welcome", "First-time pawn customer or lifelong collector, you get the same friendly counter."],
      ["Good stuff gets a second life", "Tools, watches and guitars get passed on instead of tossed out."],
    ],
    reviewsTitle: "From the regulars",
    contactTitle: "Come see us",
    reverseSplit: false,
  },
  {
    slug: "ross-mobile-mechanic",
    name: "Ross Mobile Mechanic, LLC",
    short: "Ross Mobile Mechanic",
    monogram: "RM",
    logo: "logo.webp",
    logoStyle: "mark",
    theme: "industrial",
    kind: "Mobile auto repair",
    tagline: "24/7 mobile mechanic - we come to you, no tow truck needed",
    city: "Woodburn, Oregon",
    address: "Mobile service - Woodburn and the greater Portland metro",
    cityLine: "Woodburn, OR 97071",
    phone: "(503) 442-7907",
    phoneAlt: "(971) 389-7907",
    phoneHref: "tel:+15034427907",
    email: "allfixx247@gmail.com",
    hours: [
      ["Monday - Sunday", "Open 24 hours"],
      ["Holidays", "Call to confirm"],
    ],
    website: "rossmobilepdx.com",
    websiteStatus: "HAS A WEBSITE",
    websiteNote:
      "rossmobilepdx.com is live and shares the same contact email and phone line as the Woodburn listing. Not a no-website prospect.",
    accent: "#b91c1c",
    accentDark: "#991b1b",
    about:
      "Ross Mobile Mechanic is a family-owned mobile repair service. When your vehicle breaks down we drive to you with a fully equipped truck, so you never have to arrange a tow. Straight answers, honest pricing and same-day service on trucks, trailers, tractors, generators, RVs and cars.",
    services: [
      ["24/7 roadside repair", "Breakdowns happen at any hour - we answer and we roll out."],
      ["Diagnostics", "Check-engine lights, no-starts and electrical faults, diagnosed on site."],
      ["Brakes", "Pads, rotors and calipers replaced in your driveway or job site."],
      ["Starters & alternators", "Charging and starting problems fixed without a shop visit."],
      ["Batteries & jump starts", "Battery testing, replacement and jump starts anywhere."],
      ["Belts, hoses & radiators", "Serpentine belts, radiator flushes and cooling system work."],
      ["Welding & fabrication", "Mobile welding for frames, exhausts and trailers."],
      ["Fleet & preventive maintenance", "Scheduled servicing for trucks, trailers and RV fleets."],
    ],
    highlights: [
      ["24/7", "roadside availability"],
      ["0", "tow trucks required"],
      ["Same-day", "on-site repairs"],
    ],
    reviews: [
      [
        "I'd give more stars if I could!! I had a badly blown tire with no spare. My car was in a garage with 7ft clearance four levels down.",
        "C P.",
        5,
      ],
      [
        "I had an issue with my car. It died at work and wouldn't start. It was to the point I was about to tow it home somehow... luckily someone suggested I give Ross a call\u2026",
        "Victoria J.",
        5,
      ],
    ],
    faqs: [
      ["Do you work on weekends?", "Yes - we are open 24 hours, seven days a week."],
      ["How far do you travel?", "Woodburn, Salem and the greater Portland metro area."],
      ["Can you fix it on the spot?", "Most common failures, yes. If a job needs a shop we will say so."],
    ],
    contactNote: "Call or text. Email is monitored for quotes and fleet enquiries.",
    servicesTitle: "What we fix",
    servicesIntro:
      "Trucks, trailers, tractors, RVs, generators and cars - repaired wherever you're parked.",
    servicesLead: "One truck, most repairs, and no tow bill.",
    process: {
      title: "How a house call works",
      text: "From your call to your driveway - usually the same day.",
      steps: [
        ["Call or text", "Tell us what the vehicle is doing (or not doing). We answer around the clock."],
        ["We roll out", "A fully equipped truck heads to your spot - driveway, job site or roadside."],
        ["Diagnosis first", "We find the real fault before we touch a wrench, and quote before we start."],
        ["Fixed on the spot", "Most jobs finish the same visit. If it needs a shop, we'll tell you straight."],
      ],
    },
    storyTitle: "The shop comes to you",
    values: [
      ["No tow, no queue", "Skip the tow bill and the shop wait - we come to you."],
      ["Open all hours", "Middle of the night, holiday Sunday - we answer."],
      ["Price before work", "You approve the number before we start. No surprises."],
      ["Fleet friendly", "Scheduled servicing keeps trucks, trailers and RVs moving."],
    ],
    reviewsTitle: "From real calls",
    contactTitle: "Reach us any hour",
    reverseSplit: true,
  },
  {
    slug: "key-home-improvements",
    name: "Key Home Improvements",
    short: "Key Home Improvements",
    monogram: "KH",
    logo: "",
    logoStyle: "mark",
    theme: "craft",
    kind: "Seamless gutter contractor",
    tagline: "Custom seamless gutters - more than 30 years in the trade",
    city: "Salem, Oregon",
    address: "Serving Salem and surrounding communities",
    cityLine: "Salem, OR",
    phone: "(503) 580-6868",
    phoneAlt: "(503) 391-6812",
    phoneHref: "tel:+15035806868",
    email: "yoursalemhandyman@gmail.com",
    hours: [
      ["Monday - Saturday", "7:00 am - 6:00 pm"],
      ["Sunday", "Closed"],
      ["Estimates", "Free, no charge"],
    ],
    website: "guttersforsale.com",
    websiteStatus: "HAS A WEBSITE",
    websiteNote:
      "guttersforsale.com is live, titled 'Key Home Improvements LLC', showing CCB 228717 and 503-580-6868. Not a no-website prospect.",
    accent: "#0f766e",
    accentDark: "#115e59",
    about:
      "Key Home Improvements LLC is a family-owned, licensed, bonded and insured gutter contractor run by Ron and Kelley Key. We measure your roofline, quote an exact price up front, and roll the gutter machine on site so every length fits your home exactly.",
    services: [
      ['5" and 6" K-Style gutters', "Seamless aluminum gutter run in the size your roof actually needs."],
      ["Fascia gutters", "Deep, boxy fascia profiles for a clean architectural line."],
      ["Gutter guards", "Mesh and hood systems that keep leaves out and water moving."],
      ["Gutter repairs", "Leaks, seams, sagging runs and overflowing corners fixed fast."],
      ["Gutter cleaning", "Clear-outs before the wet season so nothing overflows."],
      ["Soffit & fascia repair", "Rot, venting and trim repaired alongside the gutter work."],
      ["Residential & light commercial", "Homes, rentals, shops and small commercial buildings."],
      ["Free estimates", "No charge, no obligation - we measure and quote in the same visit."],
    ],
    highlights: [
      ["30+", "years of experience"],
      ["CCB", "#228717 licensed"],
      ["Free", "on-site estimates"],
    ],
    reviews: [
      [
        "I had new gutters installed by Ron and his crew. They were punctual, professional and did an excellent job. I'm very happy with the service and would highly recommend them.",
        "Katie S.",
        5,
      ],
    ],
    faqs: [
      ["How much do new gutters cost?", "Most homes run $6-$8 per foot, installed. We quote a firm price up front."],
      ["Do you fabricate on site?", "Yes - the seamless gutter machine comes to your driveway."],
      ["Are you licensed?", "Yes. CCB #228717, licensed, bonded and insured."],
    ],
    contactNote: "Call or text Ron directly; email for written estimates.",
    servicesTitle: "Gutter work, start to finish",
    servicesIntro:
      "Seamless gutters cut on your driveway, plus guards, repairs and cleaning before the wet season.",
    servicesLead: "Every gutter service we offer, in one plain list.",
    process: {
      title: "How a job goes",
      text: "Free estimate up front, clean work at the end.",
      steps: [
        ["Call or email Ron", "Tell us about the roofline - or send a couple of photos."],
        ["We measure and quote", "Ron measures on site and gives an exact price. Free, no obligation."],
        ["Cut on site", "The seamless machine runs in your driveway, so every length fits your home."],
        ["Done and dry", "Gutters hung, debris hauled off, driveway swept - CCB #228717 licensed work."],
      ],
    },
    storyTitle: "Ron and Kelley Key, three decades in",
    values: [
      ["One price, up front", "The number we quote is the number you pay."],
      ["Cut to fit your home", "Nothing off a shelf - every run is made for your roofline."],
      ["Licensed and insured", "CCB #228717 - licensed, bonded and insured."],
      ["Free estimates", "We measure and quote on the same visit, at no charge."],
    ],
    reviewsTitle: "From our customers",
    contactTitle: "Get a free estimate",
    reverseSplit: false,
  },
  {
    slug: "kings-cupboard",
    name: "Kings Cupboard",
    short: "Kings Cupboard",
    monogram: "KC",
    logo: "logo.jpg",
    logoStyle: "crop",
    theme: "market",
    kind: "Health food market",
    tagline: "Health food market - gluten-free, kosher and wholesome staples",
    city: "Woodburn, Oregon",
    address: "2225 N Pacific Hwy",
    cityLine: "Woodburn, OR 97071",
    phone: "(503) 981-3557",
    phoneAlt: "",
    phoneHref: "tel:+15039813557",
    email: "",
    hours: [
      ["Monday - Saturday", "8:00 am - 5:00 pm"],
      ["Sunday", "Closed"],
    ],
    website: "",
    websiteStatus: "NO WEBSITE",
    websiteNote:
      "No website found. kingscupboard.com belongs to a dessert-sauce manufacturer in Montana, and suite B at the same address is a separate business. A valid prospect.",
    accent: "#15803d",
    accentDark: "#166534",
    about:
      "Kings Cupboard is a small health food market on N Pacific Highway in Woodburn. We stock gluten-free, kosher and specialty groceries, fresh produce, supplements and everyday staples for shoppers who care about what they buy - with staff who actually know the products.",
    services: [
      ["Gluten-free groceries", "Baking mixes, pasta, snacks and staples from trusted brands."],
      ["Kosher & organic", "Certified kosher and organic pantry items and produce."],
      ["Fresh produce", "Fruit and vegetables chosen for quality, not just shelf life."],
      ["Vitamins & supplements", "Everyday supplements, herbs and wellness products."],
      ["Snacks & pantry", "Bulk snacks, oils, spices and hard-to-find specialties."],
      ["Gift & greeting cards", "Cards and small gifts for every occasion."],
    ],
    highlights: [
      ["Gluten-free", "specialist selection"],
      ["Local", "family-run market"],
      ["8 am", "early weekday opening"],
    ],
    reviews: [
      [
        "Love this little store and shop there frequently for all my pantry needs. They carry nearly every whole food pantry item I could possibly want\u2026",
        "Cev K.",
        5,
      ],
      [
        "Amazing variety of gluten-free, kosher and other healthy options. So many kinds of flours, grains, beans, seasonings, etc. this is a great place for people who cook from scratch.",
        "Deanna D.",
        4,
      ],
      [
        "It's a shame that more people don't know about this little store, because there is nothing else like it in this food wasteland that is the Woodburn/Hubbard/Canby area.",
        "Rachel G.",
        4,
      ],
    ],
    faqs: [
      ["Do you order special items?", "Ask at the counter - we can often source products we do not stock."],
      ["Are you a full grocery store?", "We are a specialty market, focused on health and specialty foods."],
      ["Where do I park?", "Plenty of free parking directly in front of the store on N Pacific Hwy."],
    ],
    contactNote: "Free parking directly in front of the store on N Pacific Highway.",
    servicesTitle: "What's on the shelves",
    servicesIntro:
      "Gluten-free, kosher, organic and from-scratch staples - picked by people who actually cook.",
    servicesLead: "What we stock, what we can order, and what we know about it.",
    process: {
      title: "How a visit goes",
      text: "Park out front, ask around, stock up.",
      steps: [
        ["Park out front", "Free parking directly in front of the store on N Pacific Highway."],
        ["Ask us anything", "We cook with this stuff ourselves - tell us what you're making and we'll point you to it."],
        ["Missing something?", "Ask at the counter. We can often order products we don't stock."],
        ["Stock up", "Pantry, produce, supplements and cards - open 8 to 5, Monday to Saturday."],
      ],
    },
    storyTitle: "There's nothing else like it around here",
    values: [
      ["Picked by cooks", "If we wouldn't take it home, it doesn't make the shelf."],
      ["Special diets, real food", "Gluten-free and kosher that still tastes like food."],
      ["Answers, not guesses", "Ask a question and get a real answer from someone who's used the product."],
      ["Open early", "Doors open at 8 a.m., Monday through Saturday."],
    ],
    reviewsTitle: "From our shoppers",
    contactTitle: "Come find us",
    reverseSplit: true,
  },
  {
    slug: "sasquatch-services",
    name: "Sasquatch Services LLC",
    short: "Sasquatch Services",
    monogram: "SS",
    logo: "",
    logoStyle: "mark",
    theme: "rugged",
    kind: "Tree service & excavation",
    tagline: "Tree removal, excavation and handyman work - licensed and insured",
    city: "Blue River, Oregon",
    address: "Serving Blue River, Leaburg and McKenzie Bridge",
    cityLine: "Blue River, OR 97413",
    phone: "(541) 285-2353",
    phoneAlt: "(541) 816-1816",
    phoneHref: "tel:+15412852353",
    email: "nic@sasquatchservicesllc.com",
    hours: [
      ["Monday - Saturday", "7:00 am - 6:00 pm"],
      ["Sunday", "Closed"],
      ["Estimates", "Free"],
    ],
    website: "",
    websiteStatus: "NO LIVE SITE",
    websiteNote:
      "sasquatchservicesllc.com is listed on their Facebook page but DNS does not resolve. Facebook only - a valid prospect.",
    accent: "#4d7c0f",
    accentDark: "#3f6212",
    about:
      "Sasquatch Services LLC is a family-owned, licensed and insured contractor based in Blue River, Oregon (CCB #244527). We take on the tough jobs - hazard trees, storm damage, overgrown land - and we are happy to work directly with your insurance company.",
    services: [
      ["Tree removal", "Large and small, including leaning hazard trees near structures."],
      ["Hazard tree assessment", "Dangerous and storm-damaged trees identified and taken down safely."],
      ["Limbing & pruning", "Crown lifting, thinning and pruning for health and clearance."],
      ["View clearance", "Open up a ridge line or river view without killing the tree."],
      ["Excavation & brush hogging", "Clearing, grading and brush cutting on rough ground."],
      ["Storm cleanup & dump runs", "Debris hauled off so your property is left clean."],
      ["Handyman & maintenance", "Year-round property maintenance for rentals and homes."],
      ["Insurance-friendly billing", "We work directly with your adjuster on covered work."],
    ],
    highlights: [
      ["CCB", "#244527 licensed"],
      ["Free", "estimates"],
      ["Insurance", "work welcome"],
    ],
    reviews: [
      [
        "Shout out to Nic @ Sasquatch Services. He is a local. Had him come by and do some digging/dirt work for us.",
        "Jennifer Baker",
        5,
      ],
    ],
    faqs: [
      ["Do you give free estimates?", "Yes. Call or email and we will schedule a walk-through at no charge."],
      ["Will you work with my insurance?", "Yes - we bill adjusters directly on covered hazard-tree work."],
      ["How far do you travel?", "Blue River, Leaburg, McKenzie Bridge and the Highway 126 corridor."],
    ],
    contactNote: "Call or email Nic for a free estimate.",
    servicesTitle: "The tough jobs",
    servicesIntro:
      "Hazard trees, storm damage and overgrown land - plus the handyman list that comes with them.",
    servicesLead: "Trees, dirt, and the jobs nobody else wants.",
    process: {
      title: "How a job starts",
      text: "From first call to a clean, cleared property.",
      steps: [
        ["Call or email Nic", "Tell us about the tree, the stumps or the hillside - photos help."],
        ["Free walk-through", "We come out, look it over and write the estimate at no charge."],
        ["We talk to your adjuster", "On covered hazard-tree work we bill your insurance directly."],
        ["Cleared and cleaned", "Trees down, land graded, debris hauled off - property left tidy."],
      ],
    },
    storyTitle: "Based in Blue River",
    values: [
      ["Free estimates", "Call or email and we'll walk the property at no charge."],
      ["Insurance-friendly", "We work directly with your adjuster on covered work."],
      ["Licensed and insured", "CCB #244527 - licensed and insured."],
      ["Local crew", "Family-owned - we live in the same valleys we work in."],
    ],
    reviewsTitle: "From a neighbor",
    contactTitle: "Call or email Nic",
    reverseSplit: false,
  },
  {
    slug: "trapala-restaurant",
    name: "Trapala Restaurant",
    short: "Trapala",
    monogram: "TR",
    logo: "logo.jpg",
    logoStyle: "mark",
    theme: "fiesta",
    kind: "Mexican restaurant",
    tagline: "Authentic Mexican food in downtown Woodburn",
    servicesNavLabel: "Menu",
    servicesPageTitle: "Our menu",
    city: "Woodburn, Oregon",
    address: "430 N 1st St",
    cityLine: "Woodburn, OR 97071",
    phone: "(503) 981-3000",
    phoneAlt: "",
    phoneHref: "tel:+15039813000",
    email: "strapala@hotmail.com",
    hours: [
      ["Monday", "Closed"],
      ["Tuesday - Saturday", "10:00 am - 8:00 pm"],
      ["Sunday", "10:00 am - 8:00 pm"],
    ],
    website: "trapala.com",
    websiteStatus: "HAS A WEBSITE",
    websiteNote:
      "trapala.com is live with a full menu and an online-ordering page. Not a no-website prospect.",
    accent: "#c2410c",
    accentDark: "#9a3412",
    about:
      "Trapala Restaurant LLC is a family-owned Mexican restaurant in downtown Woodburn, with a second location in Hubbard. We cook the traditional flavours of Mexico - meat, poultry, fish and seafood, plus vegetarian dishes - fresh every day, from recipes passed down through the family.",
    services: [
      ["Lunch & dinner", "A full menu from open to close, cooked to order."],
      ["Burritos, tacos & tortas", "The classics, made fresh and generously portioned."],
      ["Fish & seafood", "Aguachile, ceviche, shrimp and fish specials."],
      ["Vegetarian dishes", "Meat-free plates that are genuinely satisfying."],
      ["Family dining", "A relaxed, friendly room - kids welcome."],
      ["Two locations", "Downtown Woodburn and Hubbard, Oregon."],
    ],
    highlights: [
      ["180+", "reviews and counting"],
      ["2", "locations"],
      ["Fresh", "made-to-order cooking"],
    ],
    reviews: [
      ["Very good authentic Mexican food! All of the food I've tried is very delicious!", "Michael B.", 5],
      [
        "My daughter ordered the Chili Colorado Burrito and it was literally the BIGGEST burrito I have EVER seen! Humongous!",
        "Stacy A.",
        4,
      ],
      [
        "Wonderful food. Good service. I enjoyed the Pollo Ranchero. The green salsa for the chips was actually better and hotter than the red.",
        "Anthony A.",
        5,
      ],
      [
        "Everything we ordered not only looked delicious it was delicious! The portion size was a lot larger than we expected. A cutie little shop with a great atmosphere.",
        "Maria M.",
        4,
      ],
      [
        "Service here is so friendly and fast! Brought family here and have been here a few other times. Absolutely love their mango margaritas blended along with the vegetarian burrito!",
        "Sara S.",
        5,
      ],
    ],
    faqs: [
      ["Do you take reservations?", "For larger parties, yes - call ahead and we will hold a table."],
      ["Is there vegetarian food?", "Yes, several meat-free dishes and configurable plates."],
      ["Where are you located?", "430 N 1st St in downtown Woodburn, plus a second location in Hubbard."],
    ],
    contactNote: "Email is monitored; phone is best for reservations and large parties.",
    servicesTitle: "What's cooking",
    servicesIntro:
      "Huge burritos, fresh ceviche and mango margaritas - cooked to order from open to close.",
    servicesLead: "The whole menu, from the first chip to the last margarita.",
    process: {
      title: "Dining with us",
      text: "Reservations optional, appetite required.",
      steps: [
        ["Call ahead for a crowd", "Bigger party? Ring ahead and we'll hold a table."],
        ["Or just walk in", "Most nights there's a table waiting - kids welcome."],
        ["Order when you're ready", "Everything's cooked to order. Portions are generous - pace yourself."],
        ["Take some home", "Can't finish it? We'll box it up. Or find us in Hubbard too."],
      ],
    },
    storyTitle: "Recipes passed down the family",
    values: [
      ["Cooked to order", "Nothing sits under a lamp - your plate starts when you order."],
      ["Two locations", "Downtown Woodburn, and up the road in Hubbard."],
      ["Kids welcome", "A relaxed, friendly room - bring the whole table."],
      ["Fish and veggie plates", "Aguachile, ceviche and meat-free dishes that hold their own."],
    ],
    reviewsTitle: "From our diners",
    contactTitle: "Come eat with us",
    reverseSplit: true,
  },
];
